<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Seed the application's database with default categories.
     *
     * Ces catégories sont des catégories système (is_system = true)
     * partagées par tous les utilisateurs pour l'IA de catégorisation.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $categories = [
            // ==========================================
            // CATÉGORIE PAR DÉFAUT (FALLBACK)
            // ==========================================
            [
                'name' => 'Non catégorisé',
                'description' => 'Transactions en attente de catégorisation',
                'type' => 'expense',
                'color' => '#9CA3AF',
                'icon' => '❓',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 0,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ==========================================
            // CATÉGORIES DE REVENUS
            // ==========================================
            [
                'name' => 'Salaire',
                'description' => 'Revenu principal du travail',
                'type' => 'income',
                'color' => '#10B981',
                'icon' => '💼',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 1,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Freelance',
                'description' => 'Revenus de missions freelance',
                'type' => 'income',
                'color' => '#059669',
                'icon' => '💻',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 2,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Prime',
                'description' => 'Primes et bonus',
                'type' => 'income',
                'color' => '#34D399',
                'icon' => '🎁',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 3,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Investissements',
                'description' => 'Revenus d\'investissements',
                'type' => 'income',
                'color' => '#6EE7B7',
                'icon' => '📈',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 4,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Remboursements',
                'description' => 'Remboursements divers',
                'type' => 'income',
                'color' => '#A7F3D0',
                'icon' => '💰',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 5,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Vente',
                'description' => 'Vente de biens ou services',
                'type' => 'income',
                'color' => '#D1FAE5',
                'icon' => '🛍️',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 6,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Location',
                'description' => 'Revenus locatifs',
                'type' => 'income',
                'color' => '#6EE7B7',
                'icon' => '🏠',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 7,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Cadeaux reçus',
                'description' => 'Cadeaux et dons reçus',
                'type' => 'income',
                'color' => '#A7F3D0',
                'icon' => '🎉',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 8,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ==========================================
            // CATÉGORIES DE DÉPENSES - ESSENTIEL
            // ==========================================
            [
                'name' => 'Alimentation',
                'description' => 'Courses et alimentation',
                'type' => 'expense',
                'color' => '#EF4444',
                'icon' => '🛒',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 10,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Restaurants',
                'description' => 'Restaurants et livraisons',
                'type' => 'expense',
                'color' => '#DC2626',
                'icon' => '🍽️',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 11,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Logement',
                'description' => 'Loyer ou crédit immobilier',
                'type' => 'expense',
                'color' => '#B91C1C',
                'icon' => '🏠',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 12,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Charges',
                'description' => 'Charges de copropriété',
                'type' => 'expense',
                'color' => '#991B1B',
                'icon' => '🔑',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 13,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Électricité',
                'description' => 'Facture d\'électricité',
                'type' => 'expense',
                'color' => '#F59E0B',
                'icon' => '⚡',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 14,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Eau',
                'description' => 'Facture d\'eau',
                'type' => 'expense',
                'color' => '#3B82F6',
                'icon' => '💧',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 15,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Internet',
                'description' => 'Abonnement internet/box',
                'type' => 'expense',
                'color' => '#8B5CF6',
                'icon' => '🌐',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 16,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Téléphone',
                'description' => 'Forfait mobile',
                'type' => 'expense',
                'color' => '#6366F1',
                'icon' => '📱',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 17,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ==========================================
            // TRANSPORT
            // ==========================================
            [
                'name' => 'Carburant',
                'description' => 'Essence/diesel',
                'type' => 'expense',
                'color' => '#EF4444',
                'icon' => '⛽',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 20,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Transports publics',
                'description' => 'Bus, métro, train',
                'type' => 'expense',
                'color' => '#06B6D4',
                'icon' => '🚇',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 21,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Parking',
                'description' => 'Stationnement et parking',
                'type' => 'expense',
                'color' => '#0891B2',
                'icon' => '🅿️',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 22,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Taxi/VTC',
                'description' => 'Uber, Bolt, taxi',
                'type' => 'expense',
                'color' => '#0E7490',
                'icon' => '🚖',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 23,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Entretien véhicule',
                'description' => 'Réparations, révisions',
                'type' => 'expense',
                'color' => '#DC2626',
                'icon' => '🔧',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 24,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Assurance véhicule',
                'description' => 'Assurance auto/moto',
                'type' => 'expense',
                'color' => '#991B1B',
                'icon' => '🚗',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 25,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ==========================================
            // SANTÉ
            // ==========================================
            [
                'name' => 'Médecin',
                'description' => 'Consultations médicales',
                'type' => 'expense',
                'color' => '#EC4899',
                'icon' => '🩺',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 30,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Pharmacie',
                'description' => 'Médicaments et produits',
                'type' => 'expense',
                'color' => '#DB2777',
                'icon' => '💊',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 31,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Mutuelle',
                'description' => 'Assurance santé',
                'type' => 'expense',
                'color' => '#BE185D',
                'icon' => '🛡️',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 32,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Dentiste',
                'description' => 'Soins dentaires',
                'type' => 'expense',
                'color' => '#EC4899',
                'icon' => '🦷',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 33,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Opticien',
                'description' => 'Lunettes et lentilles',
                'type' => 'expense',
                'color' => '#DB2777',
                'icon' => '👓',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 34,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ==========================================
            // LOISIRS & DIVERTISSEMENT
            // ==========================================
            [
                'name' => 'Sport',
                'description' => 'Abonnement salle, activités',
                'type' => 'expense',
                'color' => '#10B981',
                'icon' => '⚽',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 40,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Streaming',
                'description' => 'Netflix, Spotify, etc.',
                'type' => 'expense',
                'color' => '#8B5CF6',
                'icon' => '📺',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 41,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Cinéma',
                'description' => 'Séances de cinéma',
                'type' => 'expense',
                'color' => '#A855F7',
                'icon' => '🎬',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 42,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sorties',
                'description' => 'Bars, concerts, événements',
                'type' => 'expense',
                'color' => '#EC4899',
                'icon' => '🎉',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 43,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Voyages',
                'description' => 'Vacances et voyages',
                'type' => 'expense',
                'color' => '#06B6D4',
                'icon' => '✈️',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 44,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Hobbies',
                'description' => 'Loisirs créatifs, matériel',
                'type' => 'expense',
                'color' => '#F59E0B',
                'icon' => '🎨',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 45,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ==========================================
            // SHOPPING
            // ==========================================
            [
                'name' => 'Vêtements',
                'description' => 'Habits et chaussures',
                'type' => 'expense',
                'color' => '#EC4899',
                'icon' => '👕',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 50,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Beauté',
                'description' => 'Coiffeur, cosmétiques',
                'type' => 'expense',
                'color' => '#F472B6',
                'icon' => '💄',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 51,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Électronique',
                'description' => 'High-tech et gadgets',
                'type' => 'expense',
                'color' => '#6366F1',
                'icon' => '💻',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 52,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Livres',
                'description' => 'Livres et magazines',
                'type' => 'expense',
                'color' => '#8B5CF6',
                'icon' => '📚',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 53,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Maison',
                'description' => 'Déco, meubles, équipement',
                'type' => 'expense',
                'color' => '#F59E0B',
                'icon' => '🛋️',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 54,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Cadeaux',
                'description' => 'Cadeaux offerts',
                'type' => 'expense',
                'color' => '#EF4444',
                'icon' => '🎁',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 55,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ==========================================
            // ÉDUCATION & ENFANTS
            // ==========================================
            [
                'name' => 'Crèche/Garderie',
                'description' => 'Garde d\'enfants',
                'type' => 'expense',
                'color' => '#F97316',
                'icon' => '👶',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 60,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Scolarité',
                'description' => 'Frais de scolarité',
                'type' => 'expense',
                'color' => '#EA580C',
                'icon' => '🎓',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 61,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Formation',
                'description' => 'Cours et formations',
                'type' => 'expense',
                'color' => '#C2410C',
                'icon' => '📖',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 62,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Fournitures scolaires',
                'description' => 'Matériel scolaire',
                'type' => 'expense',
                'color' => '#F97316',
                'icon' => '✏️',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 63,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ==========================================
            // FINANCES
            // ==========================================
            [
                'name' => 'Banque',
                'description' => 'Frais bancaires',
                'type' => 'expense',
                'color' => '#64748B',
                'icon' => '🏦',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 70,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Assurances',
                'description' => 'Autres assurances',
                'type' => 'expense',
                'color' => '#475569',
                'icon' => '🛡️',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 71,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Impôts',
                'description' => 'Impôts et taxes',
                'type' => 'expense',
                'color' => '#334155',
                'icon' => '💸',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 72,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Épargne',
                'description' => 'Virements vers épargne',
                'type' => 'expense',
                'color' => '#10B981',
                'icon' => '🐷',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 73,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Crédits',
                'description' => 'Remboursements de crédits',
                'type' => 'expense',
                'color' => '#DC2626',
                'icon' => '💳',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 74,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ==========================================
            // ANIMAUX
            // ==========================================
            [
                'name' => 'Animaux',
                'description' => 'Vétérinaire, nourriture',
                'type' => 'expense',
                'color' => '#F59E0B',
                'icon' => '🐾',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 80,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ==========================================
            // DIVERS
            // ==========================================
            [
                'name' => 'Dons',
                'description' => 'Dons et charité',
                'type' => 'expense',
                'color' => '#10B981',
                'icon' => '❤️',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 90,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Services',
                'description' => 'Services divers',
                'type' => 'expense',
                'color' => '#6B7280',
                'icon' => '🔨',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 91,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Autres dépenses',
                'description' => 'Dépenses non catégorisées',
                'type' => 'expense',
                'color' => '#9CA3AF',
                'icon' => '📦',
                'is_system' => true,
                'is_active' => true,
                'sort_order' => 99,
                'user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('categories')->insert($categories);

        $this->command->info('✅ '.count($categories).' catégories système créées avec succès !');
    }
}
